#encoding: utf-8

pups = [{:pup_name => 'Chloe', :breeder_id => '1', :breed_1 => 'Cocker Spaniel', :breed_2 => 'Poodle', :breeder_responsibility => '5', :overall_health => '5', :trainability => '3', :social_behavior => '4', :energy_level => '4', :simpatico_rating => '5', :comments => 'great dog!'},
  	 	{:pup_name => 'Spot', :breeder_id => '2', :breed_1 => 'Dalmatian', :breed_2 => 'None', :breeder_responsibility => '3', :overall_health => '3', :trainability => '3', :social_behavior => '3', :energy_level => '3', :simpatico_rating => '3', :comments => 'love my dog!'},
  	 	{:pup_name => 'Gypsy', :breeder_id => '1', :breed_1 => 'Akita', :breed_2 => 'None', :breeder_responsibility => '5', :overall_health => '4', :trainability => '3', :social_behavior => '2', :energy_level => '1', :simpatico_rating => '5', :comments => 'not very playful'},
  	 	{:pup_name => 'Jenny', :breeder_id => '2', :breed_1 => 'Dalmatian', :breed_2 => 'None', :breeder_responsibility => '3', :overall_health => '4', :trainability => '5', :social_behavior => '5', :energy_level => '3', :simpatico_rating => '4', :comments => 'very well behaved!'}]
 
breeders = [{:name => 'Justin MacMillin', :city => "Porterville", :state => 'CA', :website => 'www.com', :kennel => 'happy dogs'},
			{:name => 'Alex McGourty', :city => "San Francisco", :state => 'CA', :website => 'www.com', :kennel => 'happy dogs 2'}]

text = [
    {:title => "Mission", :body => 'Our Mission is to create a database of user-generated content about companion dogs and dog breeders, designed to help dog lovers find simpatico puppies with whom to share their homes and lives.'},
    {:title => "Background", :body => '%p Chances are good that there is a dog at your feet as you read this, just as there is one at mine.  Dogs were probably the first species to be domesticated by humans around 15,000—30,000 years ago, and since then the histories of our two species have been closely intertwined. The association between humans and dogs began as one in which dogs served various utilitarian purposes such as guarding and hunting. Today, the vast majority of our dogs fill the role of family member and companion, as opposed to serving as working dogs. But even though most dogs no longer serve a practical role in our lives, the relationship between human and dog is certainly no less deep or meaningful. Pulitzer prize-winning biologist EO Wilson popularized the concept of biophilia to describe the powerful and subconscious urge that human beings have to connect with other forms of life, and nowhere is this urge better illustrated than the desire that many people have to spend their lives with a companion dog living in their home, at their side, and sharing almost every aspect of their lives.
    %p Just as the relationship between humans and dogs has changed in recent times, so has our means of producing and acquiring them. Few dogs today are bred for their working ability. Thanks to the widespread availability of spaying and neutering and an increased awareness of the problems of dog overpopulation, responsible dog owners no longer allow their dogs to breed randomly and indiscriminately, and produce unwanted litters. But too many dogs are irresponsibly bred by small time breeders who are just trying to turn a quick profit, or by large-scale puppy mills whose puppies are marketed online or through puppy wholesalers, without an easy way for puppy seekers to evaluate whether or not the dog breeder is ethical, humane, and breeding for good health and good temperament. Still other dogs are bred by breed fanciers who breed mainly for success in the dog show ring, and then cull their less desirable show stock to be sold as “pet quality” dogs.  Good health and good temperament are to a great degree heritable in dogs, and many dogs that are bred primarily for profit or for the show ring often fall short of the ideal in terms of health and temperament. The fact that a young puppy is cute and sweet and irresistibly appealing is no assurance that it will grow up to be a healthy, suitable companion dog. Far too many dog lovers discover the heartbreak of investing a huge amount of time, money and emotional involvement in a puppy that later turns out to have serious health or behavioral problems. 
    %p Many dog lovers suggest that anyone looking for a companion dog should adopt one from a shelter. Shelter adoption offers a lifeline to those unfortunate dogs that find themselves in such desperate circumstances, and many shelter dogs make fine companions. But our ultimate goal must be to move beyond a system in which the general public acquires dogs that are largely unknown in terms of their health and temperament, were by definition irresponsibly bred (because responsible breeders do not allow the puppies they breed to end up in shelters), and have been put through the tremendous physical and emotional stress of passing through an animal shelter. Our long term goal must certainly be to create a system in which we reduce the number of irresponsibly bred dogs that end up in shelters.  Making spaying and neutering available and affordable is an important goal, but it is not sufficient to reduce the flood of dogs that enter our shelters, as long as irresponsible and strictly profit-motivated dog breeders can find a market for their puppies, and can unload their excess inventory in the night drop box of their local shelter. We also need to decrease the market share for irresponsibly bred puppies, by giving people a clear and better alternative.
    %p As a society, we have the potential to improve the way that companion dogs are produced and obtained in this country. Using technology, we can create a tool that will help dog lovers demand greater accountability with respect to the breeding of their companion dogs. Bill Gates, founder of Microsoft and global philanthropist, recently stated, “In the past year, I have been struck by how important measurement is to improving the human condition. You can achieve incredible progress if you set a clear goal and find a measure that will drive progress toward that goal.” The same must be true with respect to our companion dogs. Specialized groups have already worked diligently and successfully to develop lines of dogs specifically suited to being service dogs and working dogs of various sorts. By developing a way to measure the success of dog breeders at producing excellent companion dogs, and by giving dog owners the opportunity to provide feedback as to the suitability of their own companion dogs, we can drive the progress of improving the overall health and suitability of companion dogs in this country.  We just have to create the metric, and convince members of the dog-loving public to each take the time to contribute information about the dogs that they have owned. As an added benefit, when the market share for irresponsibly bred dogs decreases,  the number of these dogs that will end up cast off in shelters will decrease.
    %p **************************
    %p The ideal companion dog has an agreeable temperament, has good social behavior around people and other animals, and is a pleasure to be around. People who make the effort to find this website have probably had the pleasure of knowing a dog like this--the description may bring to mind the image of a Labrador retriever, or a toy poodle. You may think of a German shepherd, a sheltie, or a dog that is some blend of these breeds. I call these exceptional dogs simpatico dogs. Simpatico is a word that means like-minded, or compatible. Simpatico dogs come in all shapes and sizes, but what sets them apart is their sound health and temperament, and their desire to be with and communicate with their human family. And dogs that have these desirable qualities are generally rewarded by being able to participate extensively in the lives and activities of their human families. 
    %p So how can you maximize the chance that you will find a simpatico puppy when you make the decision to add a new canine member to your family? It is clear that good health and good temperament in dogs are, to a great degree, heritable. And although we may not all agree precisely on exactly what constitutes an “ideal temperament”, we can all agree that too many dogs lose their lives, lose their homes, or are relegated to a lonely life isolated in a back yard away from their human pack members because they are aggressive, excessively fearful or anxious, or have other recognized health, behavior or temperament problems. 
    %p This website represents an attempt to create a yardstick that will identify and recognize those dedicated dog breeders who are work tirelessly and responsibly, for the love of their breed, to creating simpatico puppies for other dog lovers to cherish and enjoy. It is an attempt to provide a way for the dog-loving public to identify and obtain carefully bred puppies that have had a healthy and well-socialized start, and that have the potential to develop into exceptional companion dogs that will enrich the lives of their forever families. It is also an attempt to improve the lives of dogs--because puppies with good health, good temperaments, and good early socialization and training will develop into dogs that can participate more fully in their owners\' lives and be treasured by them. 
    %p This site is a work in progress. It will only become a useful tool if dog lovers everywhere take the time to contribute user-generated content about the dogs that they have lived with and loved. I believe we can create a network of information and education that will benefit responsible breeders, the dog-loving public, and companion dogs alike. In the spirit of working together to achieve this goal, I welcome the input, comments and suggestions of dog lovers everywhere in order to realize it.
    %p Linda H Sanders, DVM'},
    {:title => "Goals", :body => '%p The SimpaticoPup website was created to help improve how companion puppies are produced, and how they find their way to their forever homes. We believe that:
    %p Responsible dog breeders should be willing and able to demonstrate their commitment to the following standards:
    %ul
      %li They are putting top priority on breeding dogs with excellent health and temperament, which have the potential to become excellent companion dogs to their human families.
      %li Their puppies are raised in a healthy environment, and provided with an early environment that promotes optimal socialization, behavior and development.
      %li They are willing to provide ongoing help/support to families who purchase their puppies, to facilitate the puppy’s transition into its new home and continued development. Ideally, they should be willing to provide a life-long commitment and safety net to provide for the well-being of the puppies they produce.
      %li Their breeding dogs are kept in a loving and healthy environment, where their physical, psychological and social needs are all met throughout their lives.
      %li Their breeding dogs receive adequate medical care, and have been screened for genetic/heritable health problems as recommended by the Canine Health Information Center (CHIC) http://www.caninehealthinfo.org/ 
    %p Dog lovers who are looking for a new puppy should:
    %ul  
      %li Buy a puppy only from a breeder who is willing to demonstrate that they meet all of the standards shown above.
      %li Carefully choose a puppy that will be suitable for their environment and lifestyle.
      %li Provide their puppy with a loving and healthy environment, where its physical, social and psychological needs will be met.
      %li Provide the puppy with adequate ongoing medical care and prevention.
      %li Continue the puppy’s socialization and training in order for it to develop to its full potential as a companion dog. 
      %li Provide a life-long commitment to care for the puppy, or re-home it responsibly.
    %p At SimpaticoPup.com, we believe that no one should EVER pay money for a puppy unless they verify that the breeder standards listed above are being met. Buying a dog from an irresponsible breeder supports the largely unseen and unregulated industry of puppy mills and profit-motivated breeding, in which dogs are often mistreated as livestock or cash commodities. 
    %p Dog lovers have the power to boycott irresponsible breeders, and to support only responsible breeders. If they do so, the number of irresponsible for-profit breeders will decline, the number of irresponsibly bred dogs that end up dumped into shelters as surplus inventory will decline, the health and temperament of our companion dogs will improve, and our relationships with them will be enriched. 
  %center'},
    {:title => "How You Can Help", :body => '%p 1) If you have a purebred dog (or one of the common crossbreeds that we are also collecting information on), please contribute to our website by clicking on "Rate Your Dog". This website is designed to create a large searchable database of information that will help dog lovers identify responsible dog breeders who have a track record for producing puppies that become excellent companion dogs. This user-generated content will also quantify some important characteristics for various dog breeds. It will take just a few minutes to give us some basic information about your dog\'s breed, tell us where you acquired him/her, and evaluate your dog\'s health, temperament and behavior. This information will help empower others to make a responsible choice when they seek a new puppy, and optimize their chances of finding a simpatico pup with the good health and temperament that they are looking for. It will also encourage dog breeders to prioritize good health and temperament in the puppies they produce, and recognize those responsible dog breeders who have a track record of producing healthy, well-socialized, excellent companion dogs.
    %p 2) If you decide to purchase a puppy, only purchase one from a dog breeder who is able to demonstrate that they are breeding dogs responsibly and humanely, and are producing excellent companion dogs. This website is designed to help you find such a breeder, and maximize the chances that the puppy you choose will develop into the simpatico dog that you hope for. Don\'t purchase a dog from a "middleman" such as a pet store, or a puppy broker. Many seemingly legitimate websites that offer puppies for sale are actually puppy brokers. When you buy from a broker or middleman, the accountability of the actual breeder is lost, and it is difficult to know whether that cute puppy you buy was responsibly and humanely bred, or whether it is actually the product of a profit-motivated, irresponsible and sometimes inhumane breeding operation. Furthermore, you have no idea what that puppy\'s health and temperament will be as an adult. Please do not use your dollars to support irresponsible breeding.
    %p 3) Consider adopting a dog from a shelter, if you are willing to take more of a gamble by acquiring a dog or puppy with unknown genetics, health, temperament, and behavioral traits. Many dogs end up in shelters through no fault of their own, and it is a testament to canine adaptability that a great many of these dogs can blossom and become wonderful companions and treasured family members when they finally find the right home. Until every adoptable dog that enters a shelter leaves it with a new forever family, we must continue to encourage spaying and neutering, and encourage shelter adoption for those individuals who are willing to take a leap of faith when seeking a new dog. At the same time, the database of user-generated content in this website will help discourage irresponsible breeding, which will ultimately decrease the number of dogs that pass through our shelters\' doors. 
  %center'}
]

breeders.each do |breed|
  Breeder.create!(breed)
end

pups.each do |pup|
  Pup.create!(pup)
end

text.each do |text|
  Text.create!(text)
end